### ISSUE TITLE
NodeMCU support?

### ISSUE THREAD

**Issue by JacobPritchettBB** [Palatis/Arduino-Lufa#10]
Hi,

I'm pretty new to microprocessor development. I have a NodeMCU board, however, it doesn't seem to work with Arduino-Lufa. It's ESP-12/ESP8266-based, and with that being a different architecture, compiling this software for that board without extensive modification is out of the question, correct? Or am I missing something? My Arduino IDE can compile other Arduino software onto my NodeMCU just fine.

Thanks!

**Comment by Palatis** [comment]
Short answer: **never**.

Long answer:
NodeMCU use ESP8266, which is a total different architecture (xtensa32) than AVR.
LUFA utilize hardware support exists in the MCU, only [a few models supports it](http://www.atmel.com/selector.html#(actives:!(81041,8238,8394,8362,8282,8431,8300,8358,8392,8378,8445,8236,8449,8474,8248,8264,8447,8256,8254,8286,8462,8429,8458,8466,8400,8302,8278),data:(area:'',category:'34864[33180[33085]]',pm:!((i:8238,v:!(4,14)),(i:8394,v:!(4,16)),(i:8362,v:!(12,13)),(i:8282,v:!(6)),(i:8431,v:!(6,25)),(i:8300,v:!(4,8)),(i:8358,v:!(12,56)),(i:8392,v:!(0,1)),(i:8378,v:0),(i:8445,v:!(5,6,9)),(i:8236,v:!(7,21)),(i:8449,v:!(1,6)),(i:8474,v:!(0)),(i:8248,v:!(0,1)),(i:8264,v:!(1,4)),(i:8447,v:!(0,1)),(i:8256,v:!(1)),(i:8254,v:!(8,14)),(i:8286,v:!(0,1)),(i:8462,v:!(0,4)),(i:8429,v:!(2,6)),(i:8458,v:!(0,2)),(i:8466,v:!(1,2)),(i:8400,v:!(2,12)),(i:8302,v:!(0)),(i:8278,v:!(0,1))),view:table),sc:1)).

There is no hardware USB facilities on ESP8266 (nor ESP32), even if it does, the register and behaviors would be very different than the ones on AVR.

LUFA will probably **never** supports MCUs not found in this list, thus nor this project.

For other AVR MCUs, your best best is [VUSB](https://www.obdev.at/products/vusb/index.html) project.

For esp8266, it's actually pretty interesting, I once wanted to hack out a software USB stack (**borrowing** codes from VUSB), but never really got it working.
Maybe I'll release the corpse project someday in the future when I have some free time, but it's not for newbie (not going to be a **clone-the-repo-and-it-works** project), anyway.

**Comment by JacobPritchettBB** [comment]
Thanks for the info. I ended up buying a Teensy++ 2.0, and since that has an AVR chip, LUFA is working great!
