### ISSUE TITLE
error compilation

### ISSUE THREAD

**Issue by zetropfort** [Palatis/Arduino-Lufa#12]
i install the older arduino version and the newer ,i hav the same error

Arduino : 1.8.3 (Windows 10), Carte : "Arduino/Genuino Uno"

In file included from C:\Program Files (x86)\Arduino\libraries\LUFA/LUFA/LUFA/Drivers/USB/USB.h:383:0,

                 from C:\Program Files (x86)\Arduino\libraries\LUFA/LUFA.h:11,

                 from C:\Program Files (x86)\Arduino\libraries\LUFA\examples\LUFA_DualVirtualSerial\LUFA_DualVirtualSerial.ino:9:

C:\Program Files (x86)\Arduino\libraries\LUFA/LUFA/LUFA/Drivers/USB/Core/USBMode.h:260:7: error: #error USB_DEVICE_ONLY is not available for the currently selected microcontroller model.

      #error USB_DEVICE_ONLY is not available for the currently selected microcontroller model.

       ^

C:\Program Files (x86)\Arduino\libraries\LUFA/LUFA/LUFA/Drivers/USB/Core/USBMode.h:271:6: error: #error The currently selected device, USB mode or architecture is not supported.

     #error The currently selected device, USB mode or architecture is not supported.

      ^

In file included from C:\Program Files (x86)\Arduino\libraries\LUFA/LUFA/LUFA/Drivers/USB/Core/USBController.h:150:0,

                 from C:\Program Files (x86)\Arduino\libraries\LUFA/LUFA/LUFA/Drivers/USB/Core/USBTask.h:47,

                 from C:\Program Files (x86)\Arduino\libraries\LUFA/LUFA/LUFA/Drivers/USB/USB.h:386,

                 from C:\Program Files (x86)\Arduino\libraries\LUFA/LUFA.h:11,

                 from C:\Program Files (x86)\Arduino\libraries\LUFA\examples\LUFA_DualVirtualSerial\LUFA_DualVirtualSerial.ino:9:

C:\Program Files (x86)\Arduino\libraries\LUFA/LUFA/LUFA/Drivers/USB/Core/AVR8/USBController_AVR8.h:114:5: error: #error No PLL prescale value available for chosen F_USB value and AVR model.

    #error No PLL prescale value available for chosen F_USB value and AVR model.

     ^

exit status 1
Erreur de compilation pour la carte Arduino/Genuino Uno

Ce rapport pourrait être plus détaillé avec
l'option "Afficher les résultats détaillés de la compilation"
activée dans Fichier -> Préférences.

thank for your help

**Comment by Palatis** [comment]
1. Please use English
2. UNO with a ATmega328p which doesn't include USB subsystem.
