### ISSUE TITLE
Error when verifying 

### ISSUE THREAD

**Issue by bytedeez** [Palatis/Arduino-Lufa#14]
Not 100% sure as I'm a newbie but here is the error message. I'm trying to use lufa in order to combine hid and mass storage onto one board/bootloader which is impossible with the Arduino libraries.

![lufa_Arduino_error](https://user-images.githubusercontent.com/7134028/80534090-b0913100-896c-11ea-9713-dce4d882b9de.jpg)

Edit: For error output clarification. Added pic instead of copy and pasting the error output text.

**Comment by iFreilicht** [comment]
Could you try to reformat your error output please? It's very hard to read right now.

What sketch are you trying to verify? Your own or the example from the Arduino-LUFA library?

Did you run `$ ./LUFA/activate.py` after installation? I see the Arduino libraries are sitting in you OneDrive, does the IDE actually load them from there? Does it show up as an installed library in the Arduino IDE?

**Comment by bytedeez** [comment]
@iFreilicht 

Yes I did run $./lufa/activate.py after installation.
Lufa is available as a library to choose from under the sketch tab. 
The sketch I am trying to verify is the example sketch.

I edited my first post and added an actually picture of the error output instead of the text. As github's built in editor and automated features made it easier to read than trying to edit the copied error output text. 
hope this helps as I am still scratching my head.

Edited: for grammar.

**Comment by iFreilicht** [comment]
I'll try to have a look at this within the next week, but can't guarantee anything.

Unfortunately, your image isn't helpful to me as not all errors can be seen. If formatting the output on github takes too much time, maybe just put the error message on https://pastebin.com and link that here. I do need the full output to get an idea of what's happening.

**Comment by iFreilicht** [comment]
One more thing you could try: Download the .exe installer, install the IDE that way and see if it works then. The Windows Store version is apparently 1.8.33.0, but the actual current version for the store is 1.8.11, not sure what's going on there.

I last used this lib in 2017, with 1.8.4 I believe, so maybe something changed in the Arduino core library that causes this incompatibility now.

**Comment by iFreilicht** [comment]
Ok, I think I'm starting to see what the problem is.

Could you please run `deactivate.py` and `activate.py` and post the output of `activate.py` here?
