### ISSUE TITLE
Unable to upload project

### ISSUE THREAD

**Issue by mattcrump** [Palatis/Arduino-Lufa#15]
Hi,

Followed the instructions and compiled for the Arduino Leonardo.  Uploaded and everything worked fine using the LUFA_DualVirtualSerial example.

I wanted to makes some changes, but have been unable to upload the modified project.
I get:

avrdude: butterfly_recv(): programmer is not responding

I get the same result on PORT6 and PORT7.

I've tried hitting the reset switch once the PORTS string appears, but this doesn't help.

Any thoughts on what I'm missing?

Full log here:
https://pastebin.com/j0VtwK5Y

Cheers,
Matt.

**Comment by iFreilicht** [comment]
Huh that is very strange indeed, with the reset button there should be no way for LUFA to interfere with the upload.
Are you 100% sure the reset button is working?

It seems you're on Windows, so there should be a sound when you reset the Arduino, the same that you get when you connect/disconnect a usb drive. Can you hear that sound when resetting?

Another thing you could check is the Device Manager. When resetting, it should refresh and the Arduino Bootloader should show up somewhere in there.
