### ISSUE TITLE
Just a question: Can it work on Arduino Due?

### ISSUE THREAD

**Issue by Anyeos** [Palatis/Arduino-Lufa#16]
If there are a manner of doing this in KISS mode I will appreciate to know.

And thank you anyway for the project.

**Comment by Anyeos** [comment]
For someone that are interested I just found the answer here: https://petervanhoyweghen.wordpress.com/2013/02/25/modifying-the-atmega16u2-firmware-on-the-due

Basically I need to compile a new firmware for the Arduino Due with the LUFA library included.

**Comment by iFreilicht** [comment]
It doesn't seem like it. LUFA itself is not avialable on Cortex M3 processors, which is what the Due uses.

[According to hackaday](https://hackaday.com/2011/11/11/lufa-open-source-usb-stack-now-for-nxp-arm-processors/), there is a port available made by NXP, so maybe if you clone this repo non-recursive and replace the LUFA submodule with the NXP port, it will just work, don't count on it though.
