### ISSUE TITLE
Struggling with step 2 of installation

### ISSUE THREAD

**Issue by JollyWolly** [Palatis/Arduino-Lufa#18]
There is no <arduino_install_path> library of arduino IDE

**Comment by iFreilicht** [comment]
`<arduino_install_path>` is not an arduino library, but a placeholder in the command below.

Please read carefully:

> 2. Navigate into your Arduino IDE's libraries folder. **Replace <arduino_install_path> with the install path of the Arduino IDE.**
> 
>     `$ cd <arduino_install_path>/libraries`
> 

So the command above will become something like

    $ cd C:/Programs/Arduino/libraries

However, this is different on every PC, so you have to figure out what the install path of the Arduino IDE is on your PC.

**Comment by JollyWolly** [comment]
Sorry, big derp on my part.
I dont have any experience with python, I get this on step 4
`$ ./LUFA/activate.py`
`bash: ./LUFA/activate.py: python3^M: bad interpreter: Permission denied
`

**Comment by iFreilicht** [comment]
Sounds like you don’t have python3 installed. You need Python3.3 or higher, just check what’s available on your platform. When installing on Windows, make sure you let the installer add python to your PATH and allow it to extend the limit on environment variable length.

**Comment by iFreilicht** [comment]
Ah, or if you’re running WSL, make sure you install python inside bash with apt. The version installed with the .exe installer may not be available inside WSL.
