### ISSUE TITLE
How to include other arduino libraries in a LUFA sketch?

### ISSUE THREAD

**Issue by svilex** [Palatis/Arduino-Lufa#25]
I'm trying to read an sdcard file within my lufa sketch but including the arduino \<SD\> library will give compile errors when the LUFA board is selected. What should I do to use it as I would normally do? .

**Comment by iFreilicht** [comment]
Could you please post the exact compiler errors you're seeing? Normally other libraries work just fine with LUFA.

**Comment by svilex** [comment]
I don't have the exact errors now but it's about all kinds of undefined types if included in a .c file and about undefined Serial when included in the .ino, manually removing serial usage from the library fixed it.
