### ISSUE TITLE
How to uninstall this shit from your board??????

### ISSUE THREAD

**Issue by Ahmo9345** [Palatis/Arduino-Lufa#27]

**Comment by iFreilicht** [comment]
Please read the instructions in the README. If you are struggling or have a specific issue, please describe your setup and issue in detail and also describe what you've already tried with screenshots or command line output, otherwise nobody will be able to help you.

**Comment by Ahmo9345** [comment]
I fixed it no worries just have to add a blank sketch to it but my Arduino AVR boards files were corrupted i just downgrade it and update it and now it uploads the sketch
